author: Surdarla
copyright: 2023, Surdarla
email: rlskejdk123@gmail.com
exclude_patterns:
- _build
- Thumbs.db
- .DS_Store
- '**.ipynb_checkpoints'
- .venv
execute:
  allow_errors: false
  cache: _build/.jupyter_cache
  exclude_patterns: []
  execute_notebooks: 'off'
  run_in_temp: false
  stderr_output: show
  timeout: 90
html:
  analytics:
    google_analytics_id: G-BMRNT7D57Q
  announcement: Refactoing Ongoing ...
  baseurl: https://surdarla.github.io/
  comments:
    hypothesis: false
    utterances:
      repo: surdarla/surdarla.github.io
  extra_footer: 'based on jupyter-book, last updated: 2024-10-30 10:52:20'
  favicon: ./images/logos/my_favi.png
  google_analytics_id: G-BMRNT7D57Q
  home_page_in_navbar: true
  use_edit_page_button: false
  use_issues_button: true
  use_multitoc_numbering: true
  use_repository_button: true
latex:
  latex_engine: pdflatex
  use_jupyterbook_latex: true
launch_buttons:
  binderhub_url: ''
  colab_url: ''
  jupyterhub_url: ''
  notebook_interface: jupyterlab
  thebe: false
logo: ./images/logos/surdarla-logo_old.png
only_build_toc_files: true
parse:
  myst_dmath_double_inline: false
  myst_enable_extensions:
  - amsmath
  - colon_fence
  - deflist
  - dollarmath
  - html_admonition
  - html_image
  - linkify
  - replacements
  - smartquotes
  - substitution
  - tasklist
  myst_url_schemes:
  - mailto
  - http
  - https
repository:
  branch: main
  path_to_book: ''
  url: https://github.com/surdarla/surdarla.github.io
sphinx:
  config:
    html_baseurl: https://surdarla.github.io/
    sitemap_locales:
    - None
    sitemap_url_scheme: '{link}'
  extra_extensions:
  - sphinx_comments
  - sphinx_proof
  - sphinx.ext.autodoc
  - sphinx_sitemap
  - sphinx_design
  local_extensions: null
  recursive_update: false
title: surdarla-book
